version: "3.8"

services:
  server:
    image: slidely-backend
    container_name: slidely-backend
    build:
        context: ./
        dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        env_file:
            - .env
        command: >
            sh -c "npm install && NODE_ENV=dev npm run dev"